### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by ismay** [mollyim/mollysocket#14]
Under the heading [Configuration](https://github.com/mollyim/mollysocket#configuration), there seems to be an incomplete sentence:

> It is possible to use MollySocket without the web server: see the Air Gapped mode on Android settings. In this mode MollySocket doesn't

In this mode Mollysocket doesn't ... I would like to know what it doesn't 😅.

**Comment by p1gp1g** [comment]
Thanks, I'm fixing it

**Comment by ismay** [comment]
Thanks!
