### ISSUE TITLE
Installation with cargo gives me an error

### ISSUE THREAD

**Issue by radasbona** [mollyim/mollysocket#15]
Hi,
i try to setup my own server on my raspberry pi 4. cargo install mollysocket gives me this error.

error: failed to download `mollysocket v1.1.1`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/opt/mollysocket/.cargo/registry/src/github.com-1ecc6299db9ec823/mollysocket-1.1.1/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`

**Comment by p1gp1g** [comment]
What's the version of cargo you are using ?

**Comment by radasbona** [comment]
1.46.0

Oh oh, let me guess...


Am 14. Dezember 2023 18:21:58 MEZ schrieb S1m ***@***.***>:

**Comment by p1gp1g** [comment]
I think you've found what's wrong :)

It needs cargo 1.59+ to strip the binaries

**Comment by radasbona** [comment]
Yep. 😇

I installed cargo from the apt repo. My fault...
