### ISSUE TITLE
How to setup air-gapped mode with Docker

### ISSUE THREAD

**Issue by kaibagley** [mollyim/mollysocket#16]
Hey,

I'm trying to follow INSTALL.md instructions with my Docker container. I want to use air gapped mode, so I don't have to expose another service to the internet, however I'm unsure of how to run the `connection add` command on the container. When I open bash inside the container there's no /opt/mollysocket folder, and I cannot switch to user mollysocket.

Thanks!

**Comment by p1gp1g** [comment]
Do you use docker-compose ? Else, how do you run the server command ?

**Comment by kaibagley** [comment]
Fantastic, thank you! Will I need to run this everytime I `docker compose down`/`docker compose up -d`?

**Comment by p1gp1g** [comment]
No, but if your endpoints change, you will have to. This nearly never happen with ntfy or NextPush

**Comment by kaibagley** [comment]
Amazing, thanks so much for the quick reply!

**Comment by albirs** [comment]
Hi, i have installed mollysocket in my local network in Portainer and is running "healthy"... 
on my phone i have installed the nfty App from f-droid  and Molly's UnifiedPush is set in "Air gapped - Mode

`mollysocket connection add ....` also worked for me

when i run `root@molly:/data# mollysocket connection list`
result is:

[2023-12-20T13:31:44Z INFO  mollysocket::config] No config file supplied
[src/cli/connection.rs:75] &connection = Connection {
    uuid: "dbd7xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxxxxxxxx",
    device_id: 2,
    password: "XxxxxxXXXxxXxxxX",
    endpoint: "https://ntfy.sh/XXXxxxxxXXX?up=1",
    forbidden: false,
    last_registration: OptTime(
        None,
    ),
}
root@molly:/data# 

Logs:
.
.
.
[2023-12-20T13:30:11Z WARN  rocket::launch] 🚀 Rocket has launched from http://172.19.0.2:8020
[2023-12-20T13:30:11Z INFO  mollysocket::server::connections] Starting connection for dbd7xxxxxx-xxxxxx-xxxxx-xxxxx-xxxxxxxxxxxx
[2023-12-20T13:30:11Z INFO  mollysocket::ws::websocket_connection] WebSocket handshake has been successfully completed
[2023-12-20T13:36:07Z INFO  rocket::server] GET / text/html:
[2023-12-20T13:36:07Z INFO  rocket::server::_] Matched: (discover) GET /
[2023-12-20T13:36:07Z INFO  rocket::server::_] Outcome: Success(200 OK)
[2023-12-20T13:36:07Z INFO  rocket::server::_] Response succeeded.

for me all seems right ... but i don't receive messages on time ....? only after when open molly messages com in...

how can i check that the setup is OK and the connection is working correctly and running? 
what means the "last_registration" option...?

thank you very much!

**Comment by houdini69** [comment]
In my case I got that wih unifiedPush Provider in Nextcloud, NextPush android app and Molly-unifiedpush installed in Pixel6 GrapheneOS

docker compose run mollysocket connection add xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 2 xxxxxxxxxxxxxxxxxxxxxxx "https://xxxxx.xxxx.xx/index.php/apps/uppush//push/xxxxxxxxxxxxxxxxxxxxxxxxxx"
...
[2024-01-05T20:53:03Z INFO  mollysocket::config] No config file supplied
UUID invalid or forbidden: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

infos after "add" were copied in Molly-unifiedpush

**Comment by houdini69** [comment]
Ok! I finally found how to start correctly the docker container. I then could add a new connection...
