### ISSUE TITLE
raspberry pi installation

### ISSUE THREAD

**Issue by llbstr** [mollyim/mollysocket#17]
hello and thanks for bringing all that work, I wanted to try mollysocket for limiting battery drain on my phone.

I tried the installation on my raspberry, unfortunately compiling failed, I have a rpi 3B+, surely that's not next gen and maybe this is causing the crashes. 
Compiling crashed on both 64 and 32bits versions of raspberry pi os lite. At the very end for 32bits.
This is when it crash : "Building [=======================> ] 324/325: mollysocket(bin) 

I was not able to make it work with docker, my skills are quite limited, after some tests I sticked to the readme file for cargo but ended with the compilation crash.

If you have a tip on trying something differently that'd be nice, and thanks again for all the work.

**Comment by p1gp1g** [comment]
Have you check the version of cargo you are using: https://github.com/mollyim/mollysocket/issues/15#issuecomment-1856262696

If you struggle with cargo, you can use the release builds if you want: https://github.com/mollyim/mollysocket/releases

**Comment by llbstr** [comment]
Thanks for the help, my cargo version is 1.74.1 armv7 installed with rustup. 

I tried the release build, but I get stuck with this error, "libssl.so.3: cannot open shared object file: No such file or directory debian". 

Researched it but had no luck so far.

**Comment by p1gp1g** [comment]
```
apt install -y libssl3 libsqlite3-0 ca-certificates
```

should work

**Comment by llbstr** [comment]
`apt install -y libssl3 libsqlite3-0 ca-certificates` was not possible but I had an unexpected success with dietpi os / airgapped mode / arm64 binary. Still getting notifications like "you may have new messages" and "searching for new messages" but it looks ok either from the phone side and the mollysocket connection. I'll check if I forget something if the next days.

**Comment by p1gp1g** [comment]
These messages are also present with FCM

**Comment by llbstr** [comment]
> These messages are also present with FCM

So everything's flawless! And the battery drain is gone. That was the last thing keeping me from running divestos without google play service. Thanks for the support.
