### ISSUE TITLE
You may have new messages

### ISSUE THREAD

**Issue by kaibagley** [mollyim/mollysocket#18]
Since using mollysocket for notifications rather than WebSocket, sometimes I get a Molly notification saying "You may have new messages" instead of the actual message. Happens about 50% of the time.

Im assuming this has something to do with my phone blocking Molly from connecting to the internet in the background upon being awoken by ntfy, however it only happens sometimes, and I've tried Molly with Optimized, and Unrestricted battery settings on my GrapheneOS pixel and I get the same notifications.

Does anyone know the reason for this? Or how I can work around it?

**Comment by albirs** [comment]
i think this is not a case for molly/mollysocket only:
https://social.tchncs.de/@abimelechbeutelbilch@fulda.social/111613751856546298

**Comment by p1gp1g** [comment]
This is an upstream (Signal) issue with push notifications. They do this because some device have extreme battery "optimization"

By the way, Android related issues better fit in https://github.com/mollyim/mollyim-android-unifiedpush
