### ISSUE TITLE
Can't register AirGapped MolleySocket

### ISSUE THREAD

**Issue by aodhan-domhnaill** [mollyim/mollysocket#19]
In the [INSTALL.md](https://github.com/mollyim/mollysocket/blob/main/INSTALL.md), it says,

> You will have to switch on air gapped mode on Molly (Android). It will have a command to copy to run on your server. You must run this command as user mollysocket with MOLLY_CONF=/opt/mollysocket/prod.toml.

I imagine the command should be something like this,
```
$ mollysocket connection add
error: the following required arguments were not provided:
  <ACCOUNT_ID>
  <DEVICE_ID>
  <PASSWORD>
  <ENDPOINT>

Usage: mollysocket connection add <ACCOUNT_ID> <DEVICE_ID> <PASSWORD> <ENDPOINT>
```

I have the UP version of Molly installed from F-Droid. Under Settings => Notifications => UnifiedPush, if I click Air gapped,

* the Account ID option disappears.
* Server parameters simply allows me to copy, but says "No device"
* Status says "Cannot create the linked device".

What do I do?

**Comment by p1gp1g** [comment]
https://github.com/mollyim/mollyim-android-unifiedpush/issues/6#issuecomment-1859844229

=> Use the last version of Molly (up) : https://github.com/mollyim/mollyim-android-unifiedpush/releases/tag/v6.41.3-2.up1

**Comment by aodhan-domhnaill** [comment]
Just updated the app version, but nothing changed. I rebooted my phone (GrapheneOS), toggled "Air gapped" several times, tried putting in my local server's address "http://192.168.8.142:8020", but nothing worked.

There is some error icon in the app, but I don't know how to access logs, so I can't see anything. If you help me access the logs, I can share more info.

**Comment by p1gp1g** [comment]
Disable/Enable UnifiedPush. We didn't expect the signal endpoint to be removed

**Comment by aodhan-domhnaill** [comment]
That did it. Thanks!

**Comment by p1gp1g** [comment]
You're welcome, sorry for the inconvenience. We have been surprised by the deletion of the endpoint
