### ISSUE TITLE
Syncing on Desktop App(s) dont work properly

### ISSUE THREAD

**Issue by albirs** [mollyim/mollysocket#22]
since i have mollyim-android-unifiedpush and mollysocket running on my primary deice, i'm notice that in some cases messages are not syncing properly to my linked Desktop app(s) (windows and macOS). Messages from the other side im chatting are arriving normal. 
Other thing is that on desktop app(s) im not able to pin "Note to self" in the contact list on the left side.

**Comment by p1gp1g** [comment]
This is an upstream issue (maybe even one with signal server): https://github.com/mollyim/mollyim-android/issues/231

So I'm closing :)
