### ISSUE TITLE
How to setup mollysocket with mollyim-android-unifiedpush 

### ISSUE THREAD

**Issue by Stefan538871** [mollyim/mollysocket#23]
Hey I am trying to use mollysocket to use unified push with mollyim-android-unifiedpush.

So far i launched the docker-compose file on a rasperry pi 4

I edited, the docker-compose.yml
to update the 
MOLLY_ALLOWED_UUIDS with the one which is showing in the android app
MOLLY_ALLOWED_ENDPOINTS with the ntfy.sh/sometopic url which was showing in the ntfy.sh app

mollysocket is available from the internet with some url like this http://my.tl.d:8020/ 

What am I doing wrong?
Do I need to update the docker config or is something else missing?

**Comment by p1gp1g** [comment]
You should try with the default docker-compose

**Comment by Stefan538871** [comment]
Ok, docker compose is started with default config
And restarted the molly app in android, still
Status
MollySocket server not found

as server url? do I need the ntfy.sh/topic url or the mollysocket url?
I tried bot as "server url" in the app and with both it shows "Status MollySocket server not found"

**Comment by p1gp1g** [comment]
You should give a look here: https://github.com/mollyim/mollysocket#troubleshoot

Remove and reenter the URL in molly android once done

**Comment by Stefan538871** [comment]
Sorry for the late reply, so far no success.
Could it be that mollysocket is not behind a reverse proxy?
and reachable from the internet via the exposed port 8020
instead of the default ones?

**Comment by p1gp1g** [comment]
Please use this issue tracker to report any bugs. But if you need help setting up or running mollysocket, check out the README, tutorials, or hit up the community
