### ISSUE TITLE
delayed / missing notifications

### ISSUE THREAD

**Issue by eylenburg** [mollyim/mollysocket#24]
I installed Molly-UP and set up an airgapped Mollysocket on Fly.io (https://github.com/pcrockett/mollysocket-fly).

However, I often dont get notifications until I open the app or I get a notification like an hour later.

In Molly it says the UP status is "ok". 

I gave unrestricted battery permissions to Molly and ntfy.

**Comment by eylenburg** [comment]
Some outputs from mollysocket (I have no idea what I'm doing, just trying random commands):

```
root@2866441be26398:/app# mollysocket connection list
[2024-01-26T09:06:09Z INFO  mollysocket::config] No config file supplied
[src/cli/connection.rs:75] &connection = Connection {
    uuid: "3ac5a691-9c50-4e45-92f8-54f95e40a298",
    device_id: 3,
    password: "<removed>",
    endpoint: "https://ntfy.sh/<removed>?up=1",
    forbidden: false,
    last_registration: OptTime(
        None,
    ),
}
```

```
root@2866441be26398:/app# mollysocket server     
[2024-01-26T09:09:24Z ERROR rocket::error] Rocket failed to bind network socket to given address/port.
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-0.5.0/src/error.rs:279:9:
aborting due to socket bind error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by eylenburg** [comment]
I have deleted the app and launched it again. So far no error message. Doesn't seem to be a Mollysocket bug per se. I'll keep an eye on the notifications, but hopefully this will be solved now.

**Comment by eylenburg** [comment]
Sorry, but it is still not working. I think I'm going back to Websockets...

**Comment by p1gp1g** [comment]
This can't work if you run multiple instances of mollysocket.

**Comment by p1gp1g** [comment]
If you need help setting up or running mollysocket, check out the README, tutorials, or hit up the community :)
