### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Weiterso** [mollyim/mollysocket#25]
Tried to install mollysocket; got this error:

`$ cargo install mollysocket
    Updating crates.io index
  Downloaded mollysocket v1.2.0
error: failed to parse manifest at´` `/opt/mollysocket/.cargo/registry/src/github.com-1ecc6299db9ec823/mollysocket-1.2.0/Cargo.toml`´
`Caused by:
  invalid type: unit variant, expected string only for key´` `profile.release.strip`

how to solve this? I'm trying this on a dietpi Debian GNU/Linux 11 (bullseye) x86_64

**Comment by citizenserious** [comment]
Same problem here

**Comment by p1gp1g** [comment]
https://github.com/mollyim/mollysocket/issues/15

**Comment by citizenserious** [comment]
Thanks, would be nice if you could provide install instructions for cargo too.
 
I use nextcloudpi and when using rustup it says that cargo is already installed. I installed it as user "mollysocket" anyway because I could not find a single install method other then apt-get and now i got the error: 

```
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mollysocket v1.2.0`, intermediate artifacts can be found at `/tmp/cargo-installovtAK5`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
with another temp file every time. And I stuck there now, removing the temp files, reboot, reinstall of rustup did not help.

Would be really nice if someone could give me a hand here :D

**Comment by p1gp1g** [comment]
Cargo has its own doc: https://doc.rust-lang.org/cargo/getting-started/installation.html

You need these packages : `libssl3 libsqlite3-0 ca-certificates`

**Comment by citizenserious** [comment]
Thanks for tying to help me, but I am not an advanced user, I just don't get it.
I have never heard of rust or cargo before

Where do I get this packages from you mentioned, I can't use apt-get because I do not know the password for the mollysocket user
I tried this but I just created the folders I think.
```

`Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).
To configure your current shell, run:
source "$HOME/.cargo/env"
mollysocket@nextcloudpi:~ $ source "$HOME/.cargo/env"
mollysocket@nextcloudpi:~ $ cargo new libssl3
     Created binary (application) `libssl3` package
mollysocket@nextcloudpi:~ $ cargo new libsqlite3-0
     Created binary (application) `libsqlite3-0` package
mollysocket@nextcloudpi:~ $ cargo new ca-certificates
     Created binary (application) `ca-certificates` package
mollysocket@nextcloudpi:~ $ cargo new libssl3
error: destination `/opt/mollysocket/libssl3` already exists
Use `cargo init` to initialize the directory
mollysocket@nextcloudpi:~ $ cargo init
     Created binary (application) package
mollysocket@nextcloudpi:~ $ cargo install mollysocket`
```

and I get the same error as before. 
When I install rustup in my main user I can't use it with the mollysocket user.

**Comment by p1gp1g** [comment]
I assume you are using a debian based distribution. Those 3 packages have to be installed with your system package manager, as root.

`apt install libssl3 libsqlite3-0 ca-certificates`

**Comment by citizenserious** [comment]
Yes exactly, I use raspian, which is debian.

`root@nextcloudpi:~# apt install libsqlite3-0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libsqlite3-0 is already the newest version (3.34.1-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@nextcloudpi:~# apt install ca-certificates
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@nextcloudpi:~# apt install libssl3
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libssl3
`

I am unable to install libssl3

**Comment by citizenserious** [comment]
That helped me move forward but unfortunately directly into the next error:

I tried to install lsqlite3 as root as well but the package is also not found.

```
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/opt/mollysocket/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/bin:/opt/mollysocket/.cargo/bin:/usr/local/sbin:/usr/lo                                                cal/bin:/usr/sbin:/usr/bin:/sbin:/bin" VSLANG="1033" "cc" "/tmp/rustcsDiSOc/symbols.o" "/tmp/cargo-installXCQJHE/release/deps/mollysocket-0389f912f61820c7.mollysocket.f096210fe59245f1-cgu.0                                                .rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installXCQJHE/release/deps" "-L" "/opt/mollysocket/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib"                                                 "-Wl,-Bstatic" "/opt/mollysocket/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-3f410048cea510b6.rlib" "-Wl,-Bdynamic" "                                                -lssl" "-lcrypto" "-lsqlite3" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/opt/mollysocket/.rustup/toolchains/stable-aarch64-unk                                                nown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installXCQJHE/release/deps/mollysocket-0389f912f61820c7" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,--s                                                trip-all" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lsqlite3
          collect2: error: ld returned 1 exit status


error: could not compile `mollysocket` (bin "mollysocket") due to previous error
error: failed to compile `mollysocket v1.2.0`, intermediate artifacts can be found at `/tmp/cargo-installXCQJHE`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by citizenserious** [comment]
I know I'm annoying, but know "pod.toml" is not created and so I can't configure it.

```
Installed package `mollysocket v1.2.0` (executable `mollysocket`)
mollysocket@nextcloudpi:~ $ ln -s /opt/mollysocket/.cargo/bin/mollysocket /opt/mollysocket/ms
mollysocket@nextcloudpi:~ $ MOLLY_CONF=/opt/mollysocket/prod.toml /opt/mollysocket/ms c l
thread 'main' panicked at /opt/mollysocket/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mollysocket-1.2.0/src/config.rs:131:13:
MOLLY_CONF=/opt/mollysocket/prod.toml, file not found.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mollysocket@nextcloudpi:~ $ ls -l
total 20
drwxr-xr-x 4 mollysocket mollysocket 4096 Jan 30 15:54 ca-certificates
-rw-r--r-- 1 mollysocket mollysocket  180 Jan 30 16:03 Cargo.toml
drwxr-xr-x 4 mollysocket mollysocket 4096 Jan 30 15:54 libsqlite3-0
drwxr-xr-x 4 mollysocket mollysocket 4096 Jan 30 15:54 libssl3
lrwxrwxrwx 1 mollysocket mollysocket   39 Jan 31 22:43 ms -> /opt/mollysocket/.cargo/bin/mollysocket
drwxr-xr-x 2 mollysocket mollysocket 4096 Jan 30 16:03 src
mollysocket@nextcloudpi:~ $ exit
```

If it works in the end I will write a short summary maybe someone else needs a step by step instruction as a ncp user too,

**Comment by p1gp1g** [comment]
Good catch, the file isn't created automatically since v1.2.0. If you want to use a config file, you have to create it manually.

I need to update INSTALL.md, you can open an issue for that if you want

**Comment by p1gp1g** [comment]
@citizenserious : I've updated the install doc

**Comment by citizenserious** [comment]
You are awesome will try that in a minute (:

**Comment by citizenserious** [comment]
Up and running!
Thank you very much.
You could add this to the install doc as advice for an existing server like Nextcloud:

Here's a step-by-step guide to set up a reverse proxy configuration in Apache to forward requests to your-domain.com/ms to http://127.0.0.1:8020/ while keeping the rest of the website content unchanged:

1. Open your Apache configuration file. This can typically be found at /etc/apache2/sites-available/000-default.conf or /etc/httpd/conf/httpd.conf.

2. Add the following lines to set up the reverse proxy for the specific path /ms:
   
   
   <Location /ms>
       ProxyPass http://127.0.0.1:8020/
       ProxyPassReverse http://127.0.0.1:8020/
   </Location>
   

3. Save the configuration file and restart Apache to apply the changes:
   
   
   sudo systemctl restart apache2
   

4. Test the configuration by accessing your-domain.com/ms in a web browser. Requests to /ms should now be forwarded to the backend server running on 127.0.0.1:8020.

5. Ensure that other paths on your website, such as /, continue to serve content from the original website without being proxied.

By following these steps, you can set up a reverse proxy configuration in Apache to forward requests to a specific path /ms to a backend server while maintaining the rest of the website content unchanged.
