### ISSUE TITLE
Air gapped mode: "push might break"

### ISSUE THREAD

**Issue by pcrockett** [mollyim/mollysocket#35]
In [server/web.rs](https://github.com/mollyim/mollysocket/blob/1c18f7e4a274130a6cf794d0e2e2456dfd40a328/src/server/web.rs#L168) I see this message:

> The web server is disabled, making mollysocket run in an air gapped mode. With this clients are less easy to set up and push might break.

I understand clients are less easy to set up, but could you explain "push might break?" Is there some condition that may prevent push messages from being delivered as reliably as in the normal mode?

_Context: I'm investigating [this issue](https://github.com/pcrockett/mollysocket-fly/issues/8), trying to find reasons why a person might need to restart the server after adding a connection._

**Comment by p1gp1g** [comment]
Hi !
If the distributor (eg. ntfy) changes the endpoint, then push notifications won't work until the user set the server again. Conversation and forks are known to change the endpoint from time to time for instance.

I should probably add it in the FAQ.

I hope it answers your question. Regarding the other issue, I think mollysocket logs are a good starting point to debug it :)

**Comment by pcrockett** [comment]
Thanks, I appreciate it. I do see your log statements in the code, and I already started adding instructions in my readme to look at logs when troubleshooting. 👍

**Comment by p1gp1g** [comment]
Thank you! By the way, we are introducing a fallback mechanism to UnifiedPush, when your push server is down the distributor can tell to use another one (https://codeberg.org/UnifiedPush/specifications/issues/11), and this won't be possible in air gapped mode too
