### ISSUE TITLE
How does mollysocket fit into the unified push architecture?

### ISSUE THREAD

**Issue by LoveIsGrief** [mollyim/mollysocket#4]
https://unifiedpush.org/ defines 4 components: application server, push server, distributor app,  phone application 

![image](https://github.com/mollyim/mollysocket/assets/2829538/7ab100ca-cdb3-4028-9863-cad8ad2bb5e5)

The application server pushes notifications to the push server, which pushes those to the distributor app, which in turn wakes up the phone application to deliver the data (at least that's how I understand the flow).

Where does MollySocket come in? Is it a mandatory component?

It would be nice if this information were in the README.

**Comment by p1gp1g** [comment]
Mollysocket would fit into the application server : if signal server has supported a protocol compatible with UnifiedPush like Web Push, then it would be useless. Mollysocket is then a workaround, to extend the server capabilities to be compatible with UnifiedPush. I don't know if I'm clear enough :)

**Comment by LoveIsGrief** [comment]
So, do I need a push server too? The CLI options don't seem to indicate a server to push to :thinking:

**Comment by p1gp1g** [comment]
Molly will save it for you. Mollysocket can be shared between users that doesn't use the same push server

**Comment by LoveIsGrief** [comment]
I'm sorry, but I'm unable to get UnifiedPush to work and bug reports can't be created on https://github.com/mollyim/mollyim-android-unifiedpush . It isn't clear what is needed in order to make it work.

I setup mollysocket behind an nginx reverse proxy with HTTPS. Calling the domain returns `{"mollysocket":{"version":"1.1.0"}}`. After installing Molly and trying to activate UnifiedPush, it wasn't able to until I installed ntfy as the distributor app. Now, I just see this

![endpoint](https://github.com/mollyim/mollysocket/assets/2829538/2521c627-5d78-4af9-a685-8c1f42e6b41d)

Could you provide a list of things that are necessary in order to get this to work? Maybe adding them to the README would be good too. I can't be the only one running into this problem.

**Comment by p1gp1g** [comment]
> I'm sorry, but I'm unable to get UnifiedPush to work and bug reports can't be created on https://github.com/mollyim/mollyim-android-unifiedpush

Thanks, I've fixed that

**Comment by p1gp1g** [comment]
Have you open ntfy once before doing this ? If not, open it, then go back to molly and disable/enable unifiedpush.

It should work then

**Comment by LoveIsGrief** [comment]
I figured it out and opened a PR. Will test it and see how well everything works.

Thanks for your work on this! :pray:
