### ISSUE TITLE
Providing a service?

### ISSUE THREAD

**Issue by niccokunzmann** [mollyim/mollysocket#41]
I am wondering and I would like to read it in the README:
Are you providing the service also for people who cannot host one?

I would like to read a statement about that or see a URL or have a GitHub discussion where people can share the services that they host in case they would like others to also use them. Or have a URL as the project URL.

**Comment by MrCybertux** [comment]
i know a public service it is the only one i could find but maybe someone else has seen some?

https://molly.adminforge.de

**Comment by valldrac** [comment]
It would be best to track this in our main repository, as it's closely related to an existing request there: https://github.com/mollyim/mollyim-android/issues/320
