### ISSUE TITLE
allowed_uuids = ['*'] dangerous or no?

### ISSUE THREAD

**Issue by LoveIsGrief** [mollyim/mollysocket#5]
I don't know how to get the account_uuids, so no idea which one to restrict it to. Is it dangerous to leave it to `[*]`?

**Comment by p1gp1g** [comment]
You can set the wildcard, register then list connections to get the uuid. This prevent users you don't know using your mollysocket server, this is not really dangerous.

**Comment by LoveIsGrief** [comment]
So, there could be public mollysocket servers :thinking:

Thank you for your responses.
