### ISSUE TITLE
Air gapped status OK but no notifications

### ISSUE THREAD

**Issue by kaibagley** [mollyim/mollysocket#53]
Hey,

Sorry I'm sure you get this a lot, but after reinstalling the base Molly version after the UP version was merged, I tried to re-setup Mollysocket and am having no success... I see the method has changed to using a QR code which is cool, but makes me think I might be doing it wrong

So:

- Add VAPID key generated using the command in the README as an env var in my compose.yml
- I open the localhost address for MollySocket and click "use airgapped", 
- on the phone I change delivery service to UnifiedPush and scan the qr code
- On the phone I hit "Server parameters" to copy the command, 
- KDE connect picks up the command so I paste it at the end of "docker compose run mollysocket ..."  and run
- I receive a test notification and it says "OK"

But I never receive notifications. All battery optimisation has been turned off, and it used to work before I swapped to the main Molly repo. Running the ping command gives me the test notification which makes me thing ntfy isnt comminicating with Molly properly?

Sorry if this is a ntfy issue, I thought maybe someone else has had this problem 

Thanks!

**Comment by p1gp1g** [comment]
You are in the section "_The status is "OK" or "OK: Air Gapped" but I still don't get notifications_" of the readme, you should try to disable battery optimization for Molly and ntfy, then check https://unifiedpush.org/users/troubleshooting/ and https://dontkillmyapp.com/

**Comment by kaibagley** [comment]
Yeah I have battery optimisations disabled, and can't see any ntfy issues, but now I'm noticing some other problem.. 

After scanning the qr code, I get "waiting for confirmation..." 
Then I run the server parameters command on the server, but nothing changes from the Android side, and it stays on the "Waiting for confirmation" stage. Not sure what has changed since before..

**Comment by p1gp1g** [comment]
Then you fall under _On the Android app, the status is Air gapped, waiting for test notification_. You have to debug your setup to see if your server hosting ms can reach your push server, and if you have been rate limited

**Comment by kaibagley** [comment]
Following the instructions under that section brings it to status OK, but then I still don't get notifications.

I'm also hosting my ntfy server.

Should the env variable MOLLY_ALLOWED_UUIDS be set to ["*"] or ["molly_uuid"]?

**Comment by p1gp1g** [comment]
Starts with `["uuid"]` is used to restrict who can use your mollysocket server, you don't need to change it for air gapped mode

**Comment by kaibagley** [comment]
Alright, yesterday I restarted Mollysocket for the 100th time, all I changed was the debug mode and it's working fine now... I really have no idea what it could've been other than maybe it needed a bit of time to brew

Thanks for your help!
