### ISSUE TITLE
websockets closing very fast

### ISSUE THREAD

**Issue by Menelmacar** [mollyim/mollysocket#56]
I've installed mollysocket by downloading the binary and setting it up as per the install.md as systemd service.
I'm using an apache2 reverse proxy. 
The service works and I get test notifications / push to Molly. 

I'm wondering if it's normal that the process is using i/o and cpu all the time and the log is a constant stream of opening websocket and closing. 

prod.toml:
db = '/opt/mollysocket/mollysocket.db'
allowed_endpoints = ['https://mypushserver.de']
allowed_uuids =                                            ['b00cfa88-0e25-46ef-b26e-e88b7b0d1326']
webserver = true
port = 8020

Log:
[mollysocket-log.txt](https://github.com/user-attachments/files/18022870/2e3aa3f2-0d21-4678-976f-dc113069f362.txt)

Mollylog: https://github.com/user-attachments/files/18039531/06_12-15-36-30_229.log

Prosody mod_unified_push log:
[Prosody.log.txt](https://github.com/user-attachments/files/18047859/Prosody.log.txt)

I'm on Debian stable, mollysocket 1.5.4
Molly: v7.26.1-1-FOSS on CalyxOS on  Nexus7 Android 15
The push server is a prosody module, the distributor is my xmpp app conversations .

**Comment by p1gp1g** [comment]
Do you have logs from Molly android ? It looks like it is in a loop sending registration again and again

**Comment by Menelmacar** [comment]
I updated above with some more info about the setup.
I did some tinkering and it seems this starts to happen if the app is force killed or of my android is restarted. It Stopps if I put the all in the foreground. It will then log the websocket connected and stops.
It might be an issue with the client and not the sever too. I'm curious if someone else has experienced that.

**Comment by p1gp1g** [comment]
Ok, that's important to have those logs, something seems wrong on the client side

**Comment by Menelmacar** [comment]
[06_12-15-36-30_229.log](https://github.com/user-attachments/files/18039531/06_12-15-36-30_229.log)

This is a log of molly, the beginning corresponds with the mollysocket constantly destroying and establishing a new websocket. (Molly is in foreground and background, doesn't matter) 
Then I send one message to a contact and mollysocket stays at the last log line with
`[2024-12-06T14:36:57Z INFO  mollysocket::ws::websocket_connection] WebSocket handshake has been successfully completed`

**Comment by p1gp1g** [comment]
There is a new PR in progress: https://github.com/pcrockett/mollysocket-fly/pull/17

**Comment by Menelmacar** [comment]
I wonder, should I rather report this to molly?

**Comment by p1gp1g** [comment]
@valldrac will transfer to mollyim-android it when he can

**Comment by Menelmacar** [comment]
A Noob question, but what websocket is it even that's logged here?
To the signal server?
Because this is talking via http post to my push server right? And that one will then talk to my distributor on my phone, which will wake molly if I understand correctly?

**Comment by Menelmacar** [comment]
I'm also using fedilab with it.

I've other news:
if I change the push server away from the prosody module to https://up.conversations.im and continue using conversations as distributor the issue is gone.

Also if I change the distributor to nfty the issue is gone.

So there is either a bug or incompatibility with https://modules.prosody.im/mod_unified_push.html I think?

**Comment by p1gp1g** [comment]
Is it possible you have configured your prosody module with ttl=0 ? IIRC up.conversations.im also use the same module

**Comment by p1gp1g** [comment]
This is not regarding the TTL in the header, but time before changing the endpoint. From the logs, it looks like it changes everytime there is a new request

**Comment by Menelmacar** [comment]
Hm. I didnt set anything, if I understsnd correctly it should be one day then:
https://hg.prosody.im/prosody-modules/file/04d0ab97a678/mod_unified_push/mod_unified_push.lua#l2

I will try to get debug logs if fedilab also suffers in a similar way.

**Comment by mwild1** [comment]
What backend are you using? If you're on Prosody trunk then it's probably using the [PASETO](https://github.com/paragonie/paseto) backend, which is stateless (the registration info is stored in the returned token). The token will indeed differ after each registration, because it includes a nonce.

I'm not aware that the spec requires tokens to be stable across multiple registrations (please correct me if I'm wrong!).

A workaround on the Prosody side would be to set `unified_push_backend = "jwt"` or `unified_push_backend = "storage"` (be aware that changing backend will invalidate all existing tokens).

**Comment by p1gp1g** [comment]
https://unifiedpush.org/developers/spec/android/#orgunifiedpushandroiddistributorregister
> The distributor SHOULD NOT create a new endpoint if a valid registration exist for the token and nothing has been updated.

This is not a MUST, but it may introduce buggy things

We have implemented a fix: https://github.com/mollyim/mollyim-android/pull/410

You should probably open issues for other buggy apps

**Comment by mwild1** [comment]
Thanks! A SHOULD NOT is good enough for me. I'll think about the best solution...

**Comment by Menelmacar** [comment]
@mwild1 
Yes. This is on prosody trunk. I will try another backend and see if that changes anything . And will test multible backends when I have the newest version of Molly that includes the fix .

**Comment by p1gp1g** [comment]
Fixed with https://github.com/mollyim/mollyim-android/pull/410

**Comment by Menelmacar** [comment]
I can confirm it working with the fix.  😊
Thanks @p1gp1g 👍
