### ISSUE TITLE
Fails to compile with LibreSSL

### ISSUE THREAD

**Issue by Kaleb-Reid** [mollyim/mollysocket#58]
While trying to compile on OpenBSD, I was facing an issue at the following line: https://github.com/mollyim/mollysocket/blob/637585b61fe4c8349b677c7b7ec16e1498e11cbf/src/vapid.rs#L190
According to https://github.com/sfackler/rust-openssl/blob/538a5cb737e8d83085553cac01643820dc7ff205/openssl/src/pkey.rs#L631 from the openssl-sys crate, ec_gen is supported by OpenSSL 3.0.0 and newer, but not LibreSSL. I was able to build and use MollySocket succesfully by using EcKey::generate() with the curve specified by Nid::X9_62_PRIME256V1, with no changes outside of gen_vapid_key(). Not sure if there are downsides to this over the current PKey::ec_gen() usage, but I can make a PR if there is no reason to prefer PKey::ec_gen().

**Comment by p1gp1g** [comment]
If it works fine with the other setup, you're welcome to open a PR :)
