### ISSUE TITLE
Loglevel for QR Code

### ISSUE THREAD

**Issue by BixelPitch** [mollyim/mollysocket#61]
Greetings!
Appreciate your great work!
I tinkered around a lot to see my qr code in my airgapped setup, which didn't show up. I lowered the log level to debug to find out where the problem is and boom. I saw the qr code! This is printed out as log level "info" and the default log level is "error". Maybe a note in the docs would be helpful! Or probably lower the default log level to "info"?

Cheers!

**Comment by p1gp1g** [comment]
done: https://github.com/mollyim/mollysocket/commit/9197feedd515118bfe8d6f8cb85585edf47aa588

**Comment by testershaven** [comment]
I think this was fixed a few days ago here https://github.com/mollyim/mollysocket/commit/9197feedd515118bfe8d6f8cb85585edf47aa588 

and can be closed :D
