### ISSUE TITLE
QR code doesn't work with non-standard port with Nginx

### ISSUE THREAD

**Issue by nukelf** [mollyim/mollysocket#62]
Hello guys, 
I am totally enthusiastic about molly, I have already donated and run it for a few months, but since the change from the -up version to the general version, I can't get it to run anymore.
Obviously I'm too stupid, or something is actually wrong.
I use mollysocket in a Docker with MACVLAN, i.e. its own IP (192.168.12.197). The port is set to 8020 in the Dockerfile, which is also where the web server can be reached.
An nginx proxy manager (npm) is connected in front of it, which accepts requests from port 41000 from the internet.
Before the situation with the VAPID and the QR code came up, everything was working fine, but now I get the following error message when I call up the website:

Origin doesn't seem to be correctly passed to mollysocket. Expecting https://mly.mydomain.com:41000, found https://mly.mydomain.com.
You may have forgotten to proxy pass the host value to mollysocket

I would understand, but my npm config looks like this - so I don't quite understand why :

    proxy_set_header X-Original-URL $uri;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Real-IP $remote_addr;

    set $proxy_forward_scheme http;
    set $proxy_server “192.168.12.197”;
    set $proxy_port 8020;

    proxy_pass $proxy_forward_scheme://$proxy_server:$proxy_port;

Perhaps one of you has an idea?

Thanks in advance
Lukas

**Comment by p1gp1g** [comment]
It looks like there is a bug for non-standard ports

**Comment by p1gp1g** [comment]
Try that: `proxy_set_header Host $host:$server_port;`

**Comment by p1gp1g** [comment]
Great. I'm closing the issue :+1:
